name: nf-core lint

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Nextflow
        uses: nf-core/setup-nextflow@v2

      - name: Install nf-core tools
        run: |
          python -m pip install nf-core

      - name: Run nf-core lint
        run: |
          nf-core lint .
