name: nf-test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  nf-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: 26.04.4

      - name: Setup nf-test
        uses: nf-core/setup-nf-test@v1
        with:
          version: 0.9.5

      - name: Run nf-test
        run: nf-test test
