name: CI

on:
  push:
    branches:
      - main
      - master
      - develop
      - dev
  pull_request:

jobs:
  nf-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: latest

      - name: Install nf-test
        run: |
          wget -qO- https://get.nf-test.com | bash
          sudo mv nf-test /usr/local/bin/

      - name: Check Docker
        run: docker --version

      - name: Show versions
        run: |
          java -version
          nextflow -version
          nf-test version

      - name: Run nf-test
        run: |
          nf-test test
